### ISSUE TITLE
Not working with Jannsen (J&J) Vaccine, because there's only one injection/appointment

### ISSUE THREAD

**Issue by MeFisto94** [lk3de/impftermin-checker#5]
```python
Traceback (most recent call last):
 File "~/impftermin_checker.py", line 302, in <module>
    if check_impftermin(driver=driver, dataset=data):
  File "~/impftermin_checker.py", line 227, in check_impftermin
    date_2 = datetime.strptime(dates[2][5:23], "%d.%m.%Y - %H:%M")
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data ' erforderlich' does not match format '%d.%m.%Y - %H:%M'
```

Due to the second date (or it's whole HTML) not being available, the bot crashes when trying to read that as a date.
The quick workaround is to move the alerting functions above the date check/comment the date check, a more thorough solution would probably require looking at the exact HTML though (or maybe just blindly catch that exception)

**Comment by MeFisto94** [comment]
This will be fixed by #4
